# -*- mode: ruby -*-
# vi: set ft=ruby :

## require https://github.com/oscar-stack/vagrant-hosts

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"


  config.vm.boot_timeout = 600
  config.vbguest.auto_update = true

  # configure kerberos
  config.vm.define "kerberos" do |s|
      s.vm.hostname = "kerberos.hdfs-pseidon"
      s.vm.network  :private_network, ip:  "192.169.4.60"

      #cluster will start kerberos services
      s.vm.provision "shell", path: "vagrant/scripts/kerberos.sh"
      s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
  end

   # configure client
    config.vm.define "client1" do |s|
        s.vm.hostname = "client1.hdfs-pseidon"
        s.vm.network  :private_network, ip:  "192.169.4.61"


        s.vm.provision "shell", path: "vagrant/scripts/init.sh"
        s.vm.provision "shell", path: "vagrant/scripts/client1.sh"

        s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
        s.vm.synced_folder "~/.m2", "/home/vagrant/.m2",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}

        s.vm.provider :virtualbox do |vb|
                 vb.customize ["modifyvm", :id, "--memory", "2048"]
                 vb.customize ["modifyvm", :id, "--cpus", "2"]
        end
    end


  # one node hdfs cluster
  config.vm.define "hdfs1" do |s|
      s.vm.hostname = "hdfs1.hdfs-pseidon"
      s.vm.network  :private_network, ip:  "192.169.4.62"

      s.vm.provision "shell", path: "vagrant/scripts/hdfs1.sh"

      s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}

      s.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", "3072"]
         vb.customize ["modifyvm", :id, "--cpus", "2"]
      end

  end


  ### etc hosts setup see https://github.com/oscar-stack/vagrant-hosts

  config.vm.provision :hosts do |provisioner|
      # Add a single hostname
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_localhost_hostnames = false # do not add FQDN to 127.0.0.1
  end

end

